site_name: Dimitar Dimitrov
site_url: https://drdv.github.io/

plugins:
  - blog:
      blog_toc: true
      blog_dir: blog
      post_readtime: false
      post_url_date_format: yyyy
      archive_name: archive
      archive_toc: true
      categories_name: categories
      categories_toc: true
      draft_on_serve: true

  - search

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.footer
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top

nav:
  - Index: index.md
  - CV: cv.md
  - Publications: publications.md
  - Blog:
    - blog/index.md

docs_dir: src

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - def_list
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: "#"

  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:  # Content tabs
      alternate_style: true

  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # https://github.com/pawamoy/markdown-exec
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter

  - abbr
  - md_in_html
