site_name: Dimitar Dimitrov
site_url: https://drdv.github.io/

plugins:
  - blog:
      blog_toc: true
      blog_dir: blog
      post_readtime: false
      post_url_date_format: ""
      archive_name: archive
      archive_toc: true
      categories_name: categories
      categories_toc: true
      draft_on_serve: true

  - search
  - glightbox

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.footer
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top

nav:
  - Index: index.md
  - CV: cv.md
  - Publications: publications.md
  - GPG: gpg.md
  - Blog:
    - blog/index.md

not_in_nav: |
    /blog/202411-summer-walking-challenge/README.md
    /blog/202412-python-strings/README.md

docs_dir: src

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - def_list
  - footnotes

  - pymdownx.arithmatex:
      generic: true

  - toc:
      permalink: "#"

  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  - pymdownx.snippets:
      base_path: src/snippets

  - pymdownx.tabbed:  # Content tabs
      alternate_style: true

  - admonition
  - pymdownx.details

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # https://github.com/pawamoy/markdown-exec
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter

  - abbr
  - md_in_html
