all:
	@echo "Be reasonable! Check available targets."

generate-materials:
	cd summer-walking-challenge && make generate-materials

clean-generated-materials:
	cd summer-walking-challenge && make clean-generated-materials
