include ../../Makefile.in

## Generate artifacts for all blogs
artifacts-generate:
	@cd 202411-summer-walking-challenge && $(MAKE) --no-print-directory artifacts-generate

## Clean generated artifacts for all blogs
artifacts-clean:
	@cd 202411-summer-walking-challenge && $(MAKE) --no-print-directory artifacts-clean
