all:
	@echo "Be reasonable! Check available targets."

generate-artifacts:
	cd 202411-summer-walking-challenge && make generate-artifacts

clean-generated-artifacts:
	cd 202411-summer-walking-challenge && make clean-generated-artifacts
